CREATE TABLE IF NOT EXISTS `sys_user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(50) NOT NULL,
    `password` VARCHAR(200) NOT NULL,
    `real_name` VARCHAR(50) DEFAULT NULL,
    `phone` VARCHAR(20) DEFAULT NULL,
    `email` VARCHAR(100) DEFAULT NULL,
    `avatar` VARCHAR(500) DEFAULT NULL,
    `role` VARCHAR(20) NOT NULL DEFAULT 'READER',
    `status` TINYINT NOT NULL DEFAULT 1,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE (`username`)
);

CREATE TABLE IF NOT EXISTS `book_category` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `parent_id` BIGINT NOT NULL DEFAULT 0,
    `level` TINYINT NOT NULL DEFAULT 1,
    `sort_order` INT NOT NULL DEFAULT 0,
    `status` TINYINT NOT NULL DEFAULT 1,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE (`name`, `parent_id`)
);

CREATE TABLE IF NOT EXISTS `book` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `isbn` VARCHAR(20) NOT NULL,
    `title` VARCHAR(200) NOT NULL,
    `author` VARCHAR(200) DEFAULT NULL,
    `publisher` VARCHAR(200) DEFAULT NULL,
    `publish_date` DATE DEFAULT NULL,
    `category_id` BIGINT DEFAULT NULL,
    `price` DECIMAL(10,2) DEFAULT NULL,
    `pages` INT DEFAULT NULL,
    `cover_image` VARCHAR(500) DEFAULT NULL,
    `description` CLOB DEFAULT NULL,
    `location` VARCHAR(100) DEFAULT NULL,
    `stock_total` INT NOT NULL DEFAULT 1,
    `stock_available` INT NOT NULL DEFAULT 1,
    `status` TINYINT NOT NULL DEFAULT 1,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE (`isbn`)
);

CREATE TABLE IF NOT EXISTS `borrow_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `book_id` BIGINT NOT NULL,
    `borrow_date` DATE NOT NULL,
    `due_date` DATE NOT NULL,
    `return_date` DATE DEFAULT NULL,
    `renew_count` TINYINT NOT NULL DEFAULT 0,
    `status` VARCHAR(20) NOT NULL DEFAULT 'BORROWING',
    `remark` VARCHAR(500) DEFAULT NULL,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `fine_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `borrow_id` BIGINT NOT NULL,
    `user_id` BIGINT NOT NULL,
    `amount` DECIMAL(10,2) NOT NULL,
    `reason` VARCHAR(500) DEFAULT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
    `pay_time` TIMESTAMP DEFAULT NULL,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `notice` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(200) NOT NULL,
    `content` CLOB DEFAULT NULL,
    `type` VARCHAR(20) DEFAULT NULL,
    `status` VARCHAR(20) DEFAULT NULL,
    `publisher_id` BIGINT DEFAULT NULL,
    `publish_time` TIMESTAMP DEFAULT NULL,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `publisher` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) DEFAULT NULL,
    `contact_phone` VARCHAR(20) DEFAULT NULL,
    `contact_email` VARCHAR(100) DEFAULT NULL,
    `website` VARCHAR(500) DEFAULT NULL,
    `description` CLOB DEFAULT NULL,
    `status` INT DEFAULT 1,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `sys_dept` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `parent_id` BIGINT DEFAULT 0,
    `ancestors` VARCHAR(500) DEFAULT NULL,
    `name` VARCHAR(100) NOT NULL,
    `sort_order` INT DEFAULT 0,
    `leader` VARCHAR(50) DEFAULT NULL,
    `phone` VARCHAR(20) DEFAULT NULL,
    `email` VARCHAR(100) DEFAULT NULL,
    `status` INT DEFAULT 1,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `stock_flow` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `book_id` BIGINT NOT NULL,
    `location_id` BIGINT DEFAULT NULL,
    `flow_type` VARCHAR(20) NOT NULL,
    `quantity` INT NOT NULL,
    `related_id` BIGINT DEFAULT NULL,
    `operator_id` BIGINT DEFAULT NULL,
    `remark` VARCHAR(500) DEFAULT NULL,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `bookshelf` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `code` VARCHAR(50) DEFAULT NULL,
    `dept_id` BIGINT DEFAULT NULL,
    `location` VARCHAR(200) DEFAULT NULL,
    `capacity` INT DEFAULT 0,
    `status` INT DEFAULT 1,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `bookshelf_storey` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `bookshelf_id` BIGINT NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `level_num` INT DEFAULT 1,
    `capacity` INT DEFAULT 0,
    `status` INT DEFAULT 1,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `book_location` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `storey_id` BIGINT NOT NULL,
    `code` VARCHAR(50) DEFAULT NULL,
    `book_id` BIGINT DEFAULT NULL,
    `status` VARCHAR(20) DEFAULT 'EMPTY',
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `book_resource` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `book_id` BIGINT NOT NULL,
    `file_name` VARCHAR(200) DEFAULT NULL,
    `file_path` VARCHAR(500) DEFAULT NULL,
    `file_type` VARCHAR(50) DEFAULT NULL,
    `file_size` BIGINT DEFAULT 0,
    `resource_type` VARCHAR(20) DEFAULT NULL,
    `sort_order` INT DEFAULT 0,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `book_normalize_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `book_id` BIGINT NOT NULL,
    `old_title` VARCHAR(200) DEFAULT NULL,
    `new_title` VARCHAR(200) DEFAULT NULL,
    `old_author` VARCHAR(200) DEFAULT NULL,
    `new_author` VARCHAR(200) DEFAULT NULL,
    `old_isbn` VARCHAR(20) DEFAULT NULL,
    `new_isbn` VARCHAR(20) DEFAULT NULL,
    `old_publisher` VARCHAR(200) DEFAULT NULL,
    `new_publisher` VARCHAR(200) DEFAULT NULL,
    `operator_name` VARCHAR(50) DEFAULT NULL,
    `status` VARCHAR(20) DEFAULT NULL,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `borrow_code` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(50) NOT NULL,
    `user_id` BIGINT NOT NULL,
    `book_id` BIGINT NOT NULL,
    `status` VARCHAR(20) DEFAULT 'ACTIVE',
    `expire_time` TIMESTAMP DEFAULT NULL,
    `used_time` TIMESTAMP DEFAULT NULL,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `approval_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `order_id` BIGINT DEFAULT NULL,
    `approver_id` BIGINT DEFAULT NULL,
    `action` VARCHAR(20) DEFAULT NULL,
    `comment` VARCHAR(500) DEFAULT NULL,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `permission_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT DEFAULT NULL,
    `operator_id` BIGINT DEFAULT NULL,
    `action` VARCHAR(50) DEFAULT NULL,
    `detail` VARCHAR(500) DEFAULT NULL,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `purchase_order` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `order_no` VARCHAR(50) DEFAULT NULL,
    `title` VARCHAR(200) DEFAULT NULL,
    `status` VARCHAR(20) DEFAULT 'DRAFT',
    `total_amount` DECIMAL(10,2) DEFAULT 0,
    `applicant_id` BIGINT DEFAULT NULL,
    `approve_time` TIMESTAMP DEFAULT NULL,
    `remark` VARCHAR(500) DEFAULT NULL,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `purchase_item` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `order_id` BIGINT NOT NULL,
    `book_title` VARCHAR(200) DEFAULT NULL,
    `isbn` VARCHAR(20) DEFAULT NULL,
    `author` VARCHAR(200) DEFAULT NULL,
    `publisher` VARCHAR(200) DEFAULT NULL,
    `price` DECIMAL(10,2) DEFAULT 0,
    `quantity` INT DEFAULT 1,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `purchase_template` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(200) NOT NULL,
    `content` CLOB DEFAULT NULL,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);
